-- AUTO GENERATED BY THEME SWITCHER - DO NOT EDIT
return {
    active_border   = "rgb(c0c0c0)",
    inactive_border = "rgba(1f1f1f99)",
    shadow_color    = 0xcc080808,
    rounding       = 0,
    rounding_power = 2,
}
