return {
    base     = "1e1e2e",
    mantle   = "181825",
    crust    = "11111b",
    text     = "cdd6f4",
    subtext  = "a6adc8",
    primary  = "cba6f7",
    secondary= "89b4fa",
    accent   = "f5c2e7",
    error    = "f38ba8",
    warning  = "fab387",
    success  = "a6e3a1",
    surface1 = "45475a",
    gtk_theme       = "catppuccin-mocha-mauve-standard+default",
    icon_theme      = "Papirus-Dark",
    border_active   = "cba6f7",
    border_inactive = "31324499",
    shadow_color    = "ee1e1e2e",
    rectangular     = true,
}
