return {
    base     = "262335",
    mantle   = "1a1a2e",
    crust    = "0f0e17",
    text     = "ffffff",
    subtext  = "b893ce",
    primary  = "ff7edb",
    secondary= "36f9f6",
    accent   = "fede5d",
    error    = "fe4450",
    warning  = "fede5d",
    success  = "72f1b8",
    surface1 = "495495",
    gtk_theme       = "catppuccin-mocha-pink-standard+default",
    icon_theme      = "Papirus-Dark",
    border_active   = "ff7edb",
    border_inactive = "49549599",
    shadow_color    = "ee0f0e17",
}
