#!/usr/bin/env lua
-- -----------------------------------------------------
-- CELESTIAL SHADE :: UNIFIED THEME CONTROLLER
-- -----------------------------------------------------

local home = os.getenv("HOME")
local root = home .. "/.config/hypr/themes"
local palette_dir = root .. "/palettes"
local artifact_dir = root .. "/artifact"
local state_file = root .. "/.current"

-- :: UTILITIES ::
local Utils = {}

function Utils.write_file(path, content)
    local file = io.open(path, "w")
    if not file then return false end
    file:write(content)
    file:close()
    return true
end

function Utils.read_file(path)
    local file = io.open(path, "r")
    if not file then return nil end
    local content = file:read("*all")
    file:close()
    return content and content:match("^%s*(.-)%s*$") or nil
end

function Utils.list_palettes()
    local p = io.popen('find "' .. palette_dir .. '" -name "*.lua" -exec basename {} .lua \\;')
    local themes = {}
    for file in p:lines() do
        table.insert(themes, file)
    end
    p:close()
    table.sort(themes)
    return themes
end

function Utils.load_palette(name)
    local path = palette_dir .. "/" .. name .. ".lua"
    local chunk = loadfile(path)
    if not chunk then return nil end
    return chunk()
end

-- :: GENERATORS ::
local Gen = {}

-- Helper: convert "rrggbb" hex string -> r, g, b integers
local function hex_to_rgb(hex)
    hex = hex:gsub("#", ""):sub(1, 6)
    local r = tonumber(hex:sub(1,2), 16) or 0
    local g = tonumber(hex:sub(3,4), 16) or 0
    local b = tonumber(hex:sub(5,6), 16) or 0
    return r, g, b
end

function Gen.hyprland(t)
    local content = string.format([[
$bg_base    = 0xff%s
$bg_mantle  = 0xff%s
$fg_text    = 0xff%s
$primary    = 0xff%s
$secondary  = 0xff%s
$accent     = 0xff%s
$error      = 0xff%s
$text_color = $fg_text
$primary_accent = $primary
]], t.base, t.mantle, t.text, t.primary, t.secondary, t.accent, t.error)
    Utils.write_file(artifact_dir .. "/theme.conf", content)
end

function Gen.css(t)
    local content = string.format([[
@define-color base #%s;
@define-color mantle #%s;
@define-color text #%s;
@define-color subtext #%s;
@define-color primary #%s;
@define-color secondary #%s;
@define-color accent #%s;
@define-color error #%s;
]], t.base, t.mantle, t.text, t.subtext or t.text, t.primary, t.secondary, t.accent, t.error)
    Utils.write_file(artifact_dir .. "/theme.css", content)
end

function Gen.rofi(t)
    local content = string.format([[
* {
    bg-base:    #%s;
    bg-mantle:  #%s;
    fg-text:    #%s;
    fg-sub:     #%s;
    primary:    #%s;
    secondary:  #%s;
    accent:     #%s;
    error:      #%s;
}
]], t.base, t.mantle, t.text, t.subtext or t.text, t.primary, t.secondary, t.accent, t.error)
    Utils.write_file(artifact_dir .. "/theme.rasi", content)
end

function Gen.kitty(t)
    local content = string.format([[
# vim:ft=kitty
# AUTO GENERATED BY THEME SWITCHER - DO NOT EDIT

foreground              #%s
background              #%s
selection_foreground    #%s
selection_background    #%s

cursor                  #%s
cursor_text_color       #%s

url_color               #%s

active_border_color     #%s
inactive_border_color   #%s

# black
color0  #%s
color8  #%s

# red
color1  #%s
color9  #%s

# green
color2  #%s
color10 #%s

# yellow
color3  #%s
color11 #%s

# blue
color4  #%s
color12 #%s

# magenta
color5  #%s
color13 #%s

# cyan
color6  #%s
color14 #%s

# white
color7  #%s
color15 #%s
]],
    t.text, t.base,
    t.base, t.primary,
    t.primary, t.base,
    t.secondary,
    t.border_active or t.primary,
    t.border_inactive and t.border_inactive:sub(1,6) or t.surface1 or t.mantle,
    t.mantle, t.surface1 or t.mantle,
    t.error, t.error,
    t.success or t.secondary, t.success or t.secondary,
    t.warning or t.accent, t.warning or t.accent,
    t.secondary, t.secondary,
    t.primary, t.primary,
    t.accent, t.accent,
    t.subtext or t.text, t.text)
    Utils.write_file(home .. "/.config/kitty/colors/colors.conf", content)
end

function Gen.beauty(t)
    local border_active   = t.border_active   or "cba6f7"
    local border_inactive = t.border_inactive or "31324499"
    local shadow_color    = t.shadow_color    or "ee1e1e2e"
    local rounding        = t.rectangular and 0  or nil
    local rounding_power  = t.rectangular and 2  or nil
    local rounding_line   = ""
    if rounding then
        rounding_line = string.format("    rounding       = %d,\n    rounding_power = %d,\n", rounding, rounding_power)
    end
    local content = string.format([[
-- AUTO GENERATED BY THEME SWITCHER - DO NOT EDIT
return {
    active_border   = "rgb(%s)",
    inactive_border = "rgba(%s)",
    shadow_color    = 0x%s,
%s}
]], border_active, border_inactive, shadow_color, rounding_line)
    Utils.write_file(home .. "/.config/hypr/themes/artifact/beauty_theme.lua", content)
end

function Gen.swaync(t)
    local rect = t.rectangular

    local function rgba(hex, a)
        local r, g, b = hex_to_rgb(hex)
        return string.format("rgba(%d, %d, %d, %.2f)", r, g, b, a)
    end

    local r_panel  = rect and "0px" or "16px"
    local r_notif  = rect and "0px" or "12px"
    local r_action = rect and "0px" or "10px"
    local r_close  = rect and "0px" or "6px"
    local r_btn    = rect and "0px" or "8px"

    local content = string.format(
[[/* ── swaync — AUTO GENERATED BY THEME SWITCHER ── */

.control-center {
  background: %s;
  border-radius: %s;
  border: 1px solid %s;
  color: #%s;
  margin: 8px;
  padding: 10px;
  box-shadow: 0 8px 32px %s;
}

.control-center-list { background: transparent; }

.notification-row { margin: 4px 0; }

.notification {
  background: %s;
  border-radius: %s;
  border: 1px solid %s;
  padding: 10px 14px;
  margin: 2px 0;
  transition: background 0.15s ease;
}

.notification:hover { background: %s; }

.notification.critical {
  border-color: %s;
  background: %s;
}

.notification-content { padding: 2px 0; }

.summary { font-size: 12px; font-weight: 700; color: #%s; }
.body    { font-size: 11px; font-weight: 400; color: %s; }
.time    { font-size: 10px; color: %s; }

.notification-default-action {
  background: transparent;
  border-radius: %s;
  padding: 0;
  border: none;
}

.close-button {
  background: %s;
  border-radius: %s;
  border: none;
  color: #%s;
  font-size: 12px;
  min-width: 20px;
  min-height: 20px;
  padding: 0;
}
.close-button:hover { background: %s; }

.clear-all-button {
  background: %s;
  border-radius: %s;
  border: 1px solid %s;
  color: %s;
  font-size: 11px;
  font-weight: 600;
  padding: 4px 14px;
  margin: 4px 0 2px 0;
}
.clear-all-button:hover { background: rgba(255,255,255,0.09); color: #%s; }

.do-not-disturb-button {
  background: %s;
  border-radius: %s;
  border: 1px solid %s;
  color: %s;
  padding: 4px 14px;
  margin: 4px 0;
}
.do-not-disturb-button:hover { background: %s; color: #%s; }

.notifications-group-headers { color: %s; font-size: 10px; padding: 2px 4px; }
]],
        rgba(t.base,    0.94), r_panel, rgba(t.text, 0.07), t.text, rgba(t.crust, 0.50),
        rgba(t.mantle,  0.90), r_notif, rgba(t.text, 0.06),
        rgba(t.surface1 or t.mantle, 0.95),
        rgba(t.error,   0.40), rgba(t.error, 0.08),
        t.text, rgba(t.text, 0.65), rgba(t.text, 0.35),
        r_action,
        rgba(t.error,   0.12), r_close, t.error, rgba(t.error, 0.22),
        rgba(t.text,    0.05), r_btn, rgba(t.text, 0.07), rgba(t.text, 0.60), t.text,
        rgba(t.text,    0.05), r_btn, rgba(t.text, 0.07), rgba(t.text, 0.60),
        rgba(t.primary, 0.10), t.primary,
        rgba(t.text,    0.35)
    )

    Utils.write_file(home .. "/.config/swaync/style.css", content)
end

function Gen.wlogout(t)
    local rect = t.rectangular

    local function rgba(hex, a)
        local r, g, b = hex_to_rgb(hex)
        return string.format("rgba(%d, %d, %d, %.2f)", r, g, b, a)
    end

    local r_button = rect and "0px" or "12px"

    local content = string.format([[
/* ── wlogout — AUTO GENERATED BY THEME SWITCHER ── */

* {
    background-image: none;
    box-shadow: none;
}

window {
    background-color: %s;
    background-image: none;
}

button {
    border-radius: %s;
    border-color: %s;
    border-style: solid;
    border-width: 1px;
    color: #%s;
    text-decoration-color: #%s;
    background-color: %s;
    background-repeat: no-repeat;
    background-position: center;
    background-size: 28%%;
    transition: background-color 0.2s ease,
                border-color 0.2s ease,
                box-shadow 0.2s ease;
    box-shadow: 0 0 0 transparent;
}

button:focus,
button:active,
button:hover {
    background-color: %s;
    border-color: %s;
    box-shadow: 0 0 18px %s,
                inset 0 0 12px %s;
    outline-style: none;
}

#lock {
    background-image: image(url("/usr/share/wlogout/icons/lock.png"), url("/usr/local/share/wlogout/icons/lock.png"));
}

#logout {
    background-image: image(url("/usr/share/wlogout/icons/logout.png"), url("/usr/local/share/wlogout/icons/logout.png"));
}

#suspend {
    background-image: image(url("/usr/share/wlogout/icons/suspend.png"), url("/usr/local/share/wlogout/icons/suspend.png"));
}

#hibernate {
    background-image: image(url("/usr/share/wlogout/icons/hibernate.png"), url("/usr/local/share/wlogout/icons/hibernate.png"));
}

#shutdown {
    background-image: image(url("/usr/share/wlogout/icons/shutdown.png"), url("/usr/local/share/wlogout/icons/shutdown.png"));
}

#reboot {
    background-image: image(url("/usr/share/wlogout/icons/reboot.png"), url("/usr/local/share/wlogout/icons/reboot.png"));
}
]],
        rgba(t.base,    0.85),
        r_button,
        rgba(t.primary, 0.25),
        t.text, t.text,
        rgba(t.mantle,  0.75),
        rgba(t.primary, 0.30),
        rgba(t.primary, 0.70),
        rgba(t.primary, 0.35),
        rgba(t.primary, 0.20)
    )

    Utils.write_file(home .. "/.config/wlogout/style.css", content)
end

function Gen.waybar_rect(t)
    local rect_css = home .. "/.config/waybar/rectangular.css"
    if t.rectangular then
        local bc = t.border_active or "cba6f7"
        local r, g, b = bc:sub(1,2), bc:sub(3,4), bc:sub(5,6)
        local border_color = string.format("rgba(%d, %d, %d, 0.60)",
            tonumber(r, 16), tonumber(g, 16), tonumber(b, 16))
        Utils.write_file(rect_css, string.format([[
/* ── Rectangular overrides — AUTO GENERATED ── */

window#waybar {
    border-radius: 0px;
    margin: 0px;
    margin-top: 0px;
    margin-left: 0px;
    margin-right: 0px;
    margin-bottom: 0px;
    border: none;
    border-bottom-width: 3px;
    border-bottom-style: solid;
    border-bottom-color: %s;
    box-shadow: 0 3px 0 rgba(0, 0, 0, 0.8), 0 4px 8px rgba(0, 0, 0, 0.5);
}

#workspaces button { border-radius: 0px; }

#workspaces button.active { border-radius: 0px; }

#cpu,
#memory,
#pulseaudio,
#clock,
#custom-controlcenter,
#network,
#custom-wlogout,
#custom-nepali {
    border-radius: 0px;
    border: none;
}

#tray {
    border-radius: 0px;
    border: none;
}

#tray > .needs-attention { border-radius: 0px; }

tooltip { border-radius: 0px; }
]], border_color))

    else
        Utils.write_file(rect_css, "")
    end
end

-- :: CORE LOGIC ::

local function apply_theme(name)
    print(":: Applying Palette: " .. name)
    local palette = Utils.load_palette(name)
    if not palette then
        print("Error: Palette not found")
        return
    end

    Utils.write_file(state_file, name)

    -- Generate all artifacts
    Gen.hyprland(palette)
    Gen.css(palette)
    Gen.rofi(palette)
    Gen.kitty(palette)
    Gen.beauty(palette)
    Gen.swaync(palette)
    Gen.waybar_rect(palette)
    Gen.wlogout(palette)

    -- Inject CSS variables into waybar style.css
    local waybar_dir = home .. "/.config/waybar"
    local waybar_css = waybar_dir .. "/style.css"
    local existing = Utils.read_file(waybar_css) or ""
    local stripped = existing:gsub("@define%-color%s+%S+%s+%S+;\n?", ""):gsub("^\n+", "")
    local new_vars = string.format(
        "@define-color base #%s;\n@define-color mantle #%s;\n@define-color text #%s;\n" ..
        "@define-color primary #%s;\n@define-color secondary #%s;\n" ..
        "@define-color accent #%s;\n@define-color error #%s;\n\n",
        palette.base, palette.mantle, palette.text,
        palette.primary, palette.secondary, palette.accent, palette.error)
    Utils.write_file(waybar_css, new_vars .. stripped)

    -- Swap waybar config (margins differ between rect and floating)
    if palette.rectangular then
        os.execute("cp " .. waybar_dir .. "/config-rect.jsonc " .. waybar_dir .. "/config.jsonc")
    else
        os.execute("cp " .. waybar_dir .. "/config-default.jsonc " .. waybar_dir .. "/config.jsonc")
    end

    -- Apply borders live via hyprctl
    if palette.border_active then
        os.execute("hyprctl keyword general:col.active_border 'rgb(" .. palette.border_active .. ")'")
        os.execute("hyprctl keyword general:col.inactive_border 'rgba(" .. palette.border_inactive .. ")'")
    end
    if palette.shadow_color then
        os.execute("hyprctl keyword decoration:shadow:color '0x" .. palette.shadow_color .. "'")
    end

    -- Reload Hyprland
    os.execute("hyprctl reload 2>/dev/null")

    -- Re-apply borders AFTER reload to override beauty.lua hardcoded values
    if palette.border_active then
        os.execute("hyprctl keyword general:col.active_border 'rgb(" .. palette.border_active .. ")'")
        os.execute("hyprctl keyword general:col.inactive_border 'rgba(" .. palette.border_inactive .. ")'")
    end
    if palette.shadow_color then
        os.execute("hyprctl keyword decoration:shadow:color '0x" .. palette.shadow_color .. "'")
    end

    -- Apply rounding live
    if palette.rectangular then
        os.execute("hyprctl keyword decoration:rounding 0")
    else
        os.execute("hyprctl keyword decoration:rounding 17")
    end

    -- GTK theme
    if palette.gtk_theme then
        os.execute("gsettings set org.gnome.desktop.interface gtk-theme '" .. palette.gtk_theme .. "'")
        os.execute("gsettings set org.gnome.desktop.interface icon-theme '" .. (palette.icon_theme or "Papirus-Dark") .. "'")
    end

    -- Reload waybar
    os.execute("pkill -SIGUSR2 waybar 2>/dev/null || (pkill waybar; waybar > /dev/null 2>&1 &)")

    -- Reload kitty
    os.execute("pkill -SIGUSR1 kitty 2>/dev/null")

    -- Wallpaper
    os.execute("lua " .. home .. "/.config/hypr/themes/wallpaper.lua &")

    -- Reload swaync
    os.execute("swaync-client --reload-css 2>/dev/null")

    os.execute("notify-send -u low 'Theme Switcher' 'Switched to " .. name:upper() .. "'")
    print(":: Done!")
end

local function launch_menu()
    local themes = Utils.list_palettes()
    local list_str = table.concat(themes, "\n")
    local cmd = string.format("echo '%s' | rofi -dmenu -p '  Theme' -i -theme-str 'window {width: 400px;}' -theme-str 'listview {lines: 10;}'", list_str)
    local handle = io.popen(cmd)
    local choice = handle:read("*a"):gsub("%s+$", "")
    handle:close()
    if choice and choice ~= "" then
        apply_theme(choice)
    end
end

-- :: ENTRY POINT ::
local arg1 = arg[1]

if arg1 == "--menu" then
    launch_menu()
elseif arg1 then
    apply_theme(arg1)
else
    local current = Utils.read_file(state_file) or "catppuccin"
    apply_theme(current)
end